### ISSUE TITLE
10s Delay in CrossSite Example

### ISSUE THREAD

**Issue by davidkobilnyk** [mrjoes/tornadio2#23]
When I run the crosssite example, I'm usually having a 10-second delay between loading the web page (the chat form appearing) and seeing the welcome message ("Welcome from the server. New participant joined"). I experienced this delay in Safari, Chrome, Firefox (8 and 11), and IE9. I've tried viewing on Mac and Windows 7, serving from Mac or Ubuntu.

I've timed the delay several times and it seems to be consistently about 10 seconds long. Sometimes, one of the browsers will consistently have no delay, but then another day when I try again there is a delay again. Chrome and IE9 have always given me a delay 100% of the time. I haven't seen the delay in Firefox 9 (on Windows 7) at all.

Any ideas about this issue?

**Comment by mrjoes** [comment]
Hi,

It is caused by the socket.io protocol switching, when it attempts to use best available protocol. It tries protocol for up to 5 seconds and if it fails - switches to next one. So, 10 seconds mean that it tried to use websockets and flashsocket for Chrome (or flashsocket and xhr-polling for IE).

In new socket.io version they're working on various protocol-level optimizations to establish connection faster.

**Comment by davidkobilnyk** [comment]
Thanks for the explanation, Serge!
