### ISSUE TITLE
python client for tornadio2

### ISSUE THREAD

**Issue by the1plummie** [mrjoes/tornadio2#26]
hey, this is more a feature request than an issue, but is it possible to include a python client to interact with the server? there are use cases where we need to to push some data to tornadio server programmatically and a python client woud come handy. other use cases been testing, load testing, etc.

i tried the code hosted here: http://pypi.python.org/pypi/websocket-client/0.5.0a, but i don't think it handles the handshaking protocol implemented in tornadio2.

thx.

**Comment by alp82** [comment]
This is exactly what i need too.

I found:
- http://stackoverflow.com/questions/4762086/socket-io-client-library-in-python
- https://github.com/amitu/amitu-websocket-client/blob/master/amitu/socketio_client.py
- https://github.com/invisibleroads/socketIO-client

I had no luck yet. I will give further information if i manage to get it up and running. Please do the same :)

**Comment by alp82** [comment]
According to my question on Stackoverflow (http://stackoverflow.com/questions/10950365/python-socket-io-client-for-sending-broadcast-messages-to-tornadio2-server) and to the author of tornadio2 and sockjs-tornado itself (https://groups.google.com/d/msg/sockjs/lgzxVnlth54/NbQKNEAzB5cJ), sockjs is preferable to socket.io. Therefore i will try out sockjs instead.

**Comment by the1plummie** [comment]
i actually found a solution, sorry i forgot to update this ticket. you can use this client:
http://pypi.python.org/pypi/websocket-client/0.7.0

you would have to do handshake yourself tho, here's sample code that works for me:

```
def handshake(self, host, port):
    url = "http://%s:%s/socket.io/1/" % (host, port)
    u = urllib.urlopen(url)
    if u.getcode() == 200:
        response = u.readline()
        (sid, hbtimeout, ctimeout, supported) = response.split(":")
        supportedlist = supported.split(",")
        if "websocket" in supportedlist:
            return (sid, hbtimeout, ctimeout)
        else:
            raise Exception("bad transport")
    else:
        raise Exception("invalid response")
```

(sid, hbtimeout, ctimeout) = self.handshake('localhost', '8080') #handshaking according to socket.io spec.
if int(hbtimeout) < 2:
    raise Exception("timeout received from server is too short: %s" % hbtimeout)
except Exception as e:
    logging.error('exception caught: %s' % e)
    sys.exit(1)

sock = websocket.WebSocket()
url = "ws://%s:%s/socket.io/1/websocket/%s" % ('localhost', '8080', sid)
sock.connect(url)

cheers.

**Comment by alp82** [comment]
I switched to another software stack now because of the knowledge provided in the links i posted above:
- [sockjs-client](https://github.com/sockjs/sockjs-client)
- [sockjs-tornado](https://github.com/MrJoes/sockjs-tornado)
- [redis-py](https://github.com/andymccurdy/redis-py)
- ~~[tornado-redis](https://github.com/leporo/tornado-redis)~~(bug with subscribing to channels after calling listen)
- [brukva](https://github.com/evilkost/brukva) (works like a charm as replacement to tornado-redis)

See this answer: http://stackoverflow.com/a/10950702/675065
And the corresponding blog post: http://blog.y3xz.com/post/24691592929/a-modern-python-stack-for-a-real-time-web-application
And this comparison: https://groups.google.com/d/msg/sockjs/lgzxVnlth54/NbQKNEAzB5cJ

**Comment by pkienzle** [comment]
socketIO-client, forked here, provides a pretty complete client:

```
https://github.com/scattering/socketIO-client
```

I don't know yet whether it will be a permanent fork, or whether changes will be pulled back to the original.
