### ISSUE TITLE
Access-Control-Allow-Credentials

### ISSUE THREAD

**Issue by kulik0v** [mrjoes/tornadio2#38]
In file tornadio2/preflight.py
there is a check

if 'Cookie' in self.request.headers:
    self.set_header('Access-Control-Allow-Credentials', 'true')

If I set up new server and I have no any cookie it in not working.
If I commented out this check socketio works fine.

Maybe server should add this header to response in any case if it got cookie or not.

**Comment by mrjoes** [comment]
Already fixed https://github.com/MrJoes/tornadio2/commit/4d18fd94820ecc3df25cb935e758661fdfccbe7f

Please upgrade your tornadio2.

**Comment by kulik0v** [comment]
It is another issue.
I mean to remove line

if 'Cookie' in self.request.headers:

at all.

**Comment by dop251** [comment]
The problem is that at least Safari for mac refuses to reveal the XHR response unless the Access-Control-Allow-Credentials header is 'true' even if there was no Cookie header in the request. The following message appears in the console:

XMLHttpRequest cannot load http://...... Credentials flag is true, but Access-Control-Allow-Credentials is not "true".

Removing the if 'Cookie' in self.request.headers: condition fixes the problem.

**Comment by dop251** [comment]
Aha, I can see this is already fixed as well just not in the release, sorry about that.
