### ISSUE TITLE
Documentation on Session usage

### ISSUE THREAD

**Issue by DeaconDesperado** [mrjoes/tornadio2#66]
From what I can tell, the current documentation is a little scant on how to properly implement session handling from within a router.  The structure of the code makes it a little difficult to understand how sessions are instantiated.

The chat included with the codebase gives a detailed explanation of how to persist multiple users on a singleton connection object, but does go into detail about persisting sessions or creating channels.  A practical howto would be great.

**Comment by mrjoes** [comment]
Not sure I understand the problem.

Why do you want to manage sessions by yourself? `Session` is tornadio2 internal object which encapsulates state of the logical Socket.IO connection.

`SocketConnection` is your connection class. Connection object and related session objects are automatically created during Socket.IO handshake. Whenever Socket.IO connection closes, `SocketConnection` instance and its `Session` instance will be garbage collected (unless there are references to it).

Is there particular reason you need to instantiate Session (and SocketConnection) explicitly?

**Comment by DeaconDesperado** [comment]
That explains a lot.

What I'm curious about and feel is non-obvious from the docs and examples is how to maintain separate connection state instances between users.  Take for example the `crosssite` chat example, which relies on a class-level var on the `SocketConnection` to maintain a list of users.  How could this be modified to maintain separate "chat rooms" utilizing sessions?  Where does one get the reference to a session when a user connects?  If one were to maintain separate states between different groups of users, what is the right approach if the `SocketConnection` is implemented as a singleton?  I'm sorry if I'm not being clear.

**Comment by mrjoes** [comment]
One instance of the `SocketConnection` represents one incoming client. So, if you have 10 connected users, you will have 10 `SockectConnection` instances.

You can use `self` inside of `SocketConnection` to store whatever you want - object will be alive until client drops connection.

In some cases you might want to allow your users interact with each other. In this case, one connection object should be aware about other connection objects. That's why there's "global" (class level) set with list of connected clients.

TornadIO2 does not make any assumptions on how you want to group your clients. You might want to have some fancy grouping based on tags in users profile. On by chat rooms. Or by shared roster. That's why all logical grouping should be implemented by the developer.

So, if you want rooms:
1. Create `Room` class with set of clients
2. When user connects, figure out in which room he's interested
3. Find or create room
4. Put user in a room

Whenever user sends a message, check which room it is, get it from the list of rooms and broadcast message to all room participants.

Don't forget to remove users from rooms after they disconnect.

**Comment by DeaconDesperado** [comment]
In your example, a set of `Room` instances would conceivably be a class level attribute on `SocketConnection` as well, right?  I think I may try to make up an example.

**Comment by mrjoes** [comment]
You don't have to use class level attributes. As long as all connections have shared meeting point (sort of global variable), then you're set.

Class level variable is only used to limit scope to the class in the example, nothing else.

Obviously, if you decide to scale your application over more than one server, you need to figure better meeting point (redis, amqp message bus, etc).

**Comment by DeaconDesperado** [comment]
Thanks for the help.  The implementation I was working on involved starting several separate `IOStream` instances and subscribing users to them, and I guess I got more than a little confused on the internals apart from Tornadio2.  I will close.
